### ISSUE TITLE
Quick-list quota component doesn't update on deletion/completion

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1211]
Have been deleting jobs and pools and i notice that the pool|job quota components don't update when a pool is deleted, or an active job is completed. 

![image](https://user-images.githubusercontent.com/10934358/37881685-29b877b6-30f8-11e8-8159-c04da9a25f71.png)

**Comment by timotheeguerin** [comment]
It doesn't update ever as its a pretty heavy operation potentially. You have to manually refresh it.
Also what if somebody else removed it or added it. You would need polling. But listing all pools and all jobs all the time is a bit too heavy for now. 

I don't think I'll fix this one until the new quota usage api is out.

**Comment by ascobie** [comment]
That's cool. Close it if you wish. Or just change it to feature and leave it.

**Comment by timotheeguerin** [comment]
it shows all when you click on it. Point was to only show the one closest to capacity otherwise it take way too much space

**Comment by ascobie** [comment]
closing this. can revisit at some point if someone else brings it up.
