### ISSUE TITLE
Stale pool statistics / graphs

### ISSUE THREAD

**Issue by letmaik** [Azure/BatchExplorer#1505]
**Describe the bug**
The pool statistics view (incl. graphs) is not updated immediately when pressing the various refresh buttons. I noticed this after coming back from standby on my laptop where I knew that the pool had resized from 10 to 0 nodes, but at this point I was still seeing all 10 nodes and couldn't get it to refresh easily. The refresh happened at some point but it was just very confusing as I didn't know whether there is a refresh going on or not, or when the last refresh happened.

Note that I have not checked this for other views like job stats etc. but I have a feeling it would be similar there.

**To Reproduce**
1. Create a pool with a fixed number of 10 dedicated nodes.
2. Start a resize operation to 0 nodes and stay in the pool overview view.
3. Put your machine to standby.
4. Wake your machine up after the resize is done.
5. Observe how the stats and graphs are stale and don't react to "refresh" presses.

**Expected behavior**
First, I expect that after pressing the refresh button there is a clear indicator that a refresh is happening and also when it is done. I need to know at what state of data I'm looking at (old vs current). It should also display "Last refresh: x min ago".
Then, I expect that BatchLabs has some logic like "if the last update is > x min ago, do a refresh immediately and indicate that with a spinner in the UI". This could ideally also be triggered by machine wake up. 

**Version (please complete the following information):**
 - OS: Windows
 - Version:  0.16.2-155d9ebc

**Comment by timotheeguerin** [comment]
Issue here is that the refresh is only refreshing the pool entity but not all of the sub components. 
When you are talking about pool statistics you mean the heatmap and other graphs on the pool view? There is currently no way to manually refresh(As you said it should refresh - regularly) those graph apart from navigating away from the pool then back in.
