### ISSUE TITLE
Use git tags and GitHub releases consistently

### ISSUE THREAD

**Issue by letmaik** [Azure/BatchExplorer#1506]
The last git tag (and [release entry](https://github.com/Azure/BatchExplorer/releases)) currently is 0.15.0 whereas the latest released version is 0.16.2 on https://azure.github.io/BatchExplorer/. Please keep tags and GitHub releases up to date.

**Comment by timotheeguerin** [comment]
We used to use github release to publish the binaries. This is not the case anymore. Though we could still create tags and release without the binaries(Or maybe also upload them there too).

**Comment by timotheeguerin** [comment]
Released v0.17.0 and added a github release + tag. Will keep doing so
