### ISSUE TITLE
GOVT cloud metrics charts are failing

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1550]
The monitoring charts: core minutes, failed tasks, task states, node states, dont seem to work in GOVT cloud with the following error. We should probably hide the charts in any environment where they dont work. 

Note that "current node counts" does work, so this one can stay ... 

Error loading metrics for account metrics type: coreCount
 GET https://management.usgovcloudapi.net/subscriptions/24e3df51-41b8-40da-87d3-deb5580e7f46/resourcegroups/cmu/providers/microsoft.batch/batchaccounts/projectpharrcmu/providers/Microsoft.Insights/metrics?timespan=2018-08-20T21:56:29.690Z/2018-08-20T22:56:29.690Z&interval=PT1M&metric=CoreCount,LowPriorityCoreCount&aggregation=Total,Total&api-version=2017-05-01-preview (400)
 
"microsoft.batch/batchaccounts is not a supported platform metric namespace, supported ones are Microsoft.Network/virtualNetworks,Microsoft.Network/publicIPAddresses,Microsoft.Network/networkInterfaces,Microsoft.Network/loadBalancers,Microsoft.Network/networkWatchers/connectionMonitors,Microsoft.Network/virtualNetworkGateways,Microsoft.Network/connections,Microsoft.Network/applicationGateways,Microsoft.Network/dnszones,Microsoft.Network/trafficmanagerprofiles,Microsoft.Network/expressRouteCircuits,Microsoft."

**Comment by timotheeguerin** [comment]
Should be fixed now
