### ISSUE TITLE
BatchExplorer should display what environment it is connected to

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1555]
When logged in to the govt cloud, or any other environment for that matter, it would be nice if BatchExplorer displayed the current environment in the title bar.

**Comment by timotheeguerin** [comment]
Would a checkbox here be good?

![image](https://user-images.githubusercontent.com/1031227/44937083-66395600-ad2c-11e8-9cd4-dd6849517c2a.png)
