### ISSUE TITLE
Allocation timeout error banner dissappears

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1559]
Version - Windows, 17.3 (stable).

Had an allocation timeout on a pool, there is no allocation timeout error banner displayed. If i click refresh in the pools quicklist, it shows up, then it automatically disappears again. 

clicking refresh:

![image](https://user-images.githubusercontent.com/10934358/44555122-d160b680-a787-11e8-9239-f05e0c79eac8.png)

then 5 seconds or so later: 

![image](https://user-images.githubusercontent.com/10934358/44555136-e5a4b380-a787-11e8-8d28-361d8523744a.png)

**Comment by ascobie** [comment]
actually, now i cannot replicate this .... will keep trying. Will close this issue if i cannot get it to happen again.

**Comment by ascobie** [comment]
Just grabbed a GIF of what i am seeing (look at the pool details allocation state): 

![update](https://user-images.githubusercontent.com/10934358/44634583-bf814c80-a9ef-11e8-9ec1-accb25f502c7.gif)

Doesn't seem to happen with jobs, though i have seen it once with a task, but i cannot replicate that at the moment, so it seems to be isolated to Pools ....

**Comment by timotheeguerin** [comment]
Seems to be an issue with the `GetPool` api which doesn't return the resize errors properties.
