### ISSUE TITLE
quick-list account loading appears after you click on the screen.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1560]
I have noticed this a lot recently, loading the accounts seems to be taking longer than normal, but when i click on the UI while the loading indicator is still visible, they quite often display because of me clicking on the UI. 

Seems that the UI needs a refresh to display them. Haven't noticed it on jobs or pools, just accounts. This happens a lot on my Govt cloud login as there is only 1 sub and it still takes ages to show, but when i click on the UI they magically appear.

**Comment by timotheeguerin** [comment]
This sounds like some change detection issue, will take a look

**Comment by timotheeguerin** [comment]
I was able to repro, seems to happen when you remove subscriptions and accounts from the cache
