### ISSUE TITLE
Opening BatchExplorer in Govt cloud opens 2 application windows

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1561]
Version 17.3

When i log into azure govt cloud, i quite often get 2 version of the application open at the same time ... 

![image](https://user-images.githubusercontent.com/10934358/44566400-721f9800-a7c1-11e8-9305-b0817a1f020e.png)

Sometimes closing one of them will kill both, sometimes it wont. 

I uninstalled and re-installed the app that it didnt do it the first time i logged in, but after closing and re-opening the application it now happens pretty much every time.

**Doesn't happen for public cloud ...**

**Comment by ascobie** [comment]
Am wondering if it is because we open a new window, but don't close the old one? 

`
public async updateAzureEnvironment(env: AzureEnvironment) {
        await this.aadService.logout();
        this.localStorage.setItem(Constants.localStorageKey.azureEnvironment, env.id);
        this._azureEnvironment.next(env);
        await this.aadService.login();
        **this.windows.openNewWindow();**
}
`

**Comment by timotheeguerin** [comment]
Yeah I guess that's the issue
