### ISSUE TITLE
Node pricing not showing up for manual pool creation

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1562]
The node price is not showing up in the VM picker table. At SIGGRAPH it was working for 17.1, but there were some new NC prices missing, but now, nothing seems to be showing up at all.

And while we are here ... 
 - NC_V2 machines are not showing up in the GPU tab. 
 - Compute Optimized shows (12), but nothing is in the list

Pool pricing is also not showing. This was also working at SIGGRAPH:

![image](https://user-images.githubusercontent.com/10934358/44636173-46d5bc80-a9fe-11e8-9d52-fa0939f273a7.png)

**Comment by ascobie** [comment]
**Update**

Looks like the pricing API result has changed based on what is in our codebase: 

```
    public getVMPrices(vmsize: string): VMPrices {
        vmsize = vmsize.toLowerCase();
        if (!this._map.has(vmsize)) {
            return null;
        }
        return this._map.get(vmsize);
    }
```

The _map contains this: 

![image](https://user-images.githubusercontent.com/10934358/44636634-088dcc80-aa01-11e8-9190-ed6035c5c382.png)

But we are looking for ```this._map.has('standard_d3_v2')``` which is clearly not going to work based on what is actually in the map.

**Comment by ascobie** [comment]
This is also interesting. Only pricing for Linux nodes is coming back. Windows pricing seems to only consist of standard_d40_v3 for every region.

![image](https://user-images.githubusercontent.com/10934358/44637448-4856b300-aa05-11e8-877e-6b77271b4d7a.png)

**Comment by timotheeguerin** [comment]
This looks like rate card api made AGAIN a breaking change without changing version....
