### ISSUE TITLE
Python not handling all CLI errors

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1577]
Submitting a NCJ template job seems to be hanging. Looking at the python log i am seeing this error: 

![image](https://user-images.githubusercontent.com/10934358/44890146-3474bf00-ad2d-11e8-85d1-ed627b6a92cb.png)

Which must mean that i am using an out of date CLI extension for dev. But the submit button just carries on and doesn't return the error: 

![image](https://user-images.githubusercontent.com/10934358/44890181-540be780-ad2d-11e8-8572-552e79192dc6.png)

Should we be able to trap and return this error to the user?

**Comment by timotheeguerin** [comment]
don't think this error needs to be caught. Its indeed because you haven't updated your python dependency which is something that should never happen to a user

**Comment by ascobie** [comment]
well i was more thinking that maybe other errors might enable this same result, but maybe not .... will see if i can replicate it under a difference scenario.
