### ISSUE TITLE
Cloning tasks having issue with user identity

### ISSUE THREAD

**Issue by schoenemeyer** [Azure/BatchExplorer#1616]
I am unable to clone tasks. This Feature worked fine in Batch Labs, but fails in the Batch Explorer.
The Problem can be easily reproduced. Just create a Task , run it and try to clone it afterwards. The editor produces an error message.
Cheers,
Thomas

**Comment by timotheeguerin** [comment]
Thanks for reporting, was able to repro. As a workaround now you can switch to the json editor and remove the user identity from the task.
![image](https://user-images.githubusercontent.com/1031227/45839140-5b893580-bcc8-11e8-80b8-27e55b8440fa.png)

I'll have a fix soon

**Comment by timotheeguerin** [comment]
Could you confirm this is fixed for you by downloading the artifacts of the pull request?
https://azurebatch.visualstudio.com/BatchExplorer/_build/results?buildId=1148&view=logs

![image](https://user-images.githubusercontent.com/1031227/45840790-dbb19a00-bccc-11e8-8f2b-f175409b38d7.png)

**Comment by schoenemeyer** [comment]
Many thanks, Timothee.
Problem is fixed and cloning works as expected!
Thomas

Von: Timothee Guerin <notifications@github.com>
Gesendet: Donnerstag, 20. September 2018 21:01
An: Azure/BatchExplorer <BatchExplorer@noreply.github.com>
Cc: Thomas Schoenemeyer <Thomas.Schoenemeyer@microsoft.com>; Author <author@noreply.github.com>
Betreff: Re: [Azure/BatchExplorer] Cloning tasks having issue with user identity (#1616)


Could you confirm this is fixed for you by downloading the artifacts of the pull request?
https://azurebatch.visualstudio.com/BatchExplorer/_build/results?buildId=1148&view=logs<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazurebatch.visualstudio.com%2FBatchExplorer%2F_build%2Fresults%3FbuildId%3D1148%26view%3Dlogs&data=02%7C01%7Cthomas.schoenemeyer%40microsoft.com%7C7212d6e60fc74200494008d61f2b71de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636730668791824509&sdata=XlOJTw6LdgUZdtRDB7zSMA3busu6HAXGwcNSIOc0J58%3D&reserved=0>

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1031227%2F45840790-dbb19a00-bccc-11e8-8f2b-f175409b38d7.png&data=02%7C01%7Cthomas.schoenemeyer%40microsoft.com%7C7212d6e60fc74200494008d61f2b71de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636730668791824509&sdata=6pCU9Ch41eS8IEqTwHNPbCo7lyS1O2GnqxUvclzvdpY%3D&reserved=0>
