### ISSUE TITLE
Batch Explorer: Cloning of Batch Pools does not work

### ISSUE THREAD

**Issue by schoenemeyer** [Azure/BatchExplorer#1650]
Cloning of Batch Pools with Batch Explorer does not work; in BatchLabs it is possible
1. Create an arbitrary pool in Azure Batch (e.g. Standard A4 with docker on ubuntu)
2. Try to clone the pool by clcick on clone and provide a new Name, save and close
3. See error

Best regards,
Thomas Schoenemeyer

**Comment by timotheeguerin** [comment]
Sorry about that, was able to reproduce
![image](https://user-images.githubusercontent.com/1031227/46297462-92294080-c551-11e8-9c34-9ffadfff372a.png)

**Comment by timotheeguerin** [comment]
Fix an issue with cloning pools, I'll release 0.18.2 in the next few days. If you want to get it now you can download it here https://azurebatch.visualstudio.com/BatchExplorer/_build/results?buildId=1261&view=logs and let me know if that fixed it for you too.
