### ISSUE TITLE
Colour contrast of favourites icon is too low

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchExplorer#1746]
**Describe the bug**

The colour contrast between the new favourite item "star" ⭐️ and the blue selection bar is too low.

For users with normal vision, it looks like this:

![d6552759](https://user-images.githubusercontent.com/1272094/48094006-d527b380-e275-11e8-8ae0-6d9d12d91362.PNG)

However, I don't have normal vision - I have a colour vision defect. Using a [simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/), I can show you what it looks like for me (deuteranomaly):

![image](https://user-images.githubusercontent.com/1272094/48094763-dfe34800-e277-11e8-85a8-b85e61c836c6.png)

And what it would look like for my son (protanopia):

![image](https://user-images.githubusercontent.com/1272094/48094676-a90d3200-e277-11e8-9776-d338685a13b8.png)

For someone with monochromancy, the star would be invisible!

![image](https://user-images.githubusercontent.com/1272094/48094656-998de900-e277-11e8-95f0-e1fccf03d4ac.png)

**Note**: This is a simulator that gives an approximation; colour vision defects vary in degree from person to person.

**Comment by timotheeguerin** [comment]
It is a bit tricky to have a color here that works for both background. I added a broder around the start for the selected rows.

![image](https://user-images.githubusercontent.com/1031227/48098233-f2ef0d00-e1d0-11e8-8f35-5d8b18ee2d8b.png)
