### ISSUE TITLE
File group creation disabled if no batch account selected

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1750]
Insiders Build

When submitting a job from a plugin, the create/upload file-group form is shown, the conditional logic for this is in the job submission NCJ page. The action buttons used to be automatically enabled in this form, but now they are disabled and i need to click on them to get them to enable. No amount of clicking on the other form elements will enable the buttons.

![image](https://user-images.githubusercontent.com/10934358/48169012-6b330b00-e356-11e8-8aaf-65fb4d42ec28.png)

The other worrying thing is that the upload doesn't ever work. It sits there forever like this: 

![image](https://user-images.githubusercontent.com/10934358/48169043-81d96200-e356-11e8-8704-b73e85bd2d6a.png)

Ta

**Comment by ascobie** [comment]
oh hang on. it's because no batch account is selected. we should maybe have a more aggressive warning at the top of the application UI for this. As under normal operation, the user cannot navigate anywhere if there is no user selected. but when loaded from a plugin using a ms-batch-explorer:// URL, the UI can load anywhere even if there is no default account selected.

**Comment by timotheeguerin** [comment]
Maybe we could show a dialog popup if no account is selected and you get to another page that way you don't loose the navigation
