### ISSUE TITLE
Switching from auto-scaling to fixed scaling doesn't set the node count

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#1751]
**Describe the bug**
Switching from auto-scaling to fixed scaling doesn't set the node count

**To Reproduce**
1. Ensure pool has auto-scaling formula applied (in portal)
2. Go to the pool in Batch Explorer
3. Click Resize button
4. Switch from Auto scaling to Fixed tab
5. Set number of dedicated nodes to 1
6. Press save

**Expected behavior**
Get message that pool has been scaled to 1 node, pool scales up

**Actual behaviour**
Get message that pool has scaled to 0 nodes, and the auto-scaling formula is still used instead of fixed scaling

**Version (please complete the following information):**
 - OS: Windows
 - Version: 0.18.3-stable.99

**Comment by timotheeguerin** [comment]
So seems like there is a few problems with the rescale. Fixed the most breaking one which is you can toggle between autoscale and fixed. Will be in `0.18.4` release. Created a new one #1754 for handling the delay between disabling autoscale and being able to call resize

**Comment by chrisalexander** [comment]
Thank you!
