### ISSUE TITLE
Can't view images from task node file explorer

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1756]
Development version (master) ... 

After task completes, go to Task Outputs tab, click on image, image does not load into viewer. 

One thing of note is that the filename is called: "wd\images\Test_Farm_Scene3.jpg.0001", which gives the "This file is not a known extension. Do you still want to open it?"  selector, to which i select "image". This always used to work, but doesn't appear to be working any more as the image wont load. 

Another request would be to show a loading progress indicator, as some rendering outputs are fairly large and even when this was working, it would sit there for ages downloading the file before it is shown. 

Account: andrew1973
Job: maya-arnold-windows-mel-test-1

I will keep the node around for the next 24 hours so you can debug it. After that i can re-create the job at any time should you need it.

Ta

**Comment by ascobie** [comment]
comment, checked another container (from data menu). It will load images that have a normal image extension (blender-kohler-large/outputs/final/frame_1.png), so maybe it is due to the filename ending in a non-valid extension. 

But this always used to work, so it needs to continue to do so.

**Comment by timotheeguerin** [comment]
Seems like it doesn't register which viewer to use when extension is unkown

**Comment by timotheeguerin** [comment]
Yeah that was the issue, fixed it but the loading though is working(Shows a loading indicator when the image loads) can you check it is not working for you?

**Comment by ascobie** [comment]
yeah, the loading indicator is working when it opens a valid image. Was just wondering if maybe we could show a progress indicator rather than the standard loading spinner. 

when uploading or downloading, showing the % progress is more helpful than just an indicator that "something" is happening.

**Comment by timotheeguerin** [comment]
oh I see, will take a look
