### ISSUE TITLE
Clicking item in quick-list doesn't work on the first click.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1757]
Development (master),

[Issue]
Go to a quick-list with a lot of items. In this case the Data menu (file groups) in my andrew1973 account. Scroll to the bottom of the list and select the fgrp-outputs container.

[Result]
List will scroll to the top and the first item in the list will be highlighted, but not selected.

**Comment by timotheeguerin** [comment]
hhm intreseting sounds like a secondary effect of making the list accessible
