### ISSUE TITLE
Prep task status is always failure even when completed

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1765]
Development (master)

Viewing the job prep and release tasks ALWAYS shows a failed status in the UI. Logging the state of the task shows "completed", so something is not right here.

![image](https://user-images.githubusercontent.com/10934358/48386418-c732d080-e756-11e8-88fe-34099d553e9d.png)

Logging the state shows: "STATE ::  completed"

**Comment by ascobie** [comment]
status: this.status(task), 

status is always set to "failure", but the task state is completed. So maybe its no longer an enum.

**Comment by timotheeguerin** [comment]
I see, issue with the result changed from being pascal case to lower case
