### ISSUE TITLE
Viewing a folder with lots of files in it (>10k) errors

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#1766]
**Describe the bug**
Viewing a folder with lots of files in it (>10k) errors

**To Reproduce**
1. Go to a running task which has >10k files in one of the node directories
2. Navigate to that folder in the Task Outputs view

**Expected behavior**
Shows list of files (used to do this)

**Actual behaviour**
Errors with orange message box, "Cannot read property "jobId" of null"

**Version (please complete the following information):**
 - OS: Windows
 - Version 0.18.3-stable.99

**Comment by timotheeguerin** [comment]
Does this happens all the time you browse this task? Could you share a bit more of the errors in the console? `ctrl+shift+i`

**Comment by ascobie** [comment]
Hi @chrisalexander,

We have been able to replicate the issue for any number of files above 999 on the node. We are investigating the actual cause and I believe that a fix will be out shortly. 

Thanks

**Comment by chrisalexander** [comment]
Sorry I missed the first message. Thanks for sorting! :)
