### ISSUE TITLE
Navigating to a job for the first time make an extra call with undefined jobId

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1770]
Development (master)

Manually create a job. Once the job has added, it's selected in the quicklist, but this query is used to find any tasks for it: 

```https://andrew1973.australiaeast.batch.azure.com/jobs/undefined/tasks?$select=id,state,creationTime,lastModified,executionInfo```

Note that the jobId is missing from the URL.

It does sort itself out next time you click on the job.

**Update**
Actually it doesn't sort itself out. There must be multiple /tasks queries going on. As the one that initially failed is still firing in the background.

**The query gets fired every time i click on the job in the bookmark bar.**

Go to task, click on job from the bookmark bar and 2 /tasks queries will be fired: 

![image](https://user-images.githubusercontent.com/10934358/48454347-c57f1080-e81b-11e8-91bd-42b587bdb6e3.png)

One has the jobId and one doesn't.

Reproducible

**Comment by timotheeguerin** [comment]
I think the problem is it tries to load the tasks before the job id is provided. Removing the fetchNExt from NgOnINit fixes it.
