### ISSUE TITLE
Terminate task context menu has incorrect text

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1777]
Development: 

Right click terminate running task has some curious text: 

![image](https://user-images.githubusercontent.com/10934358/48521251-a2fefd00-e8d8-11e8-91a6-ad5791b6c2c8.png)

**Comment by timotheeguerin** [comment]
Restart the app. It only detect the translation files on startup.

**Comment by ascobie** [comment]
has that recently changed?

**Comment by timotheeguerin** [comment]
It has been like that since I added localization support. Because of the cost of discovering loc file it only scan at the begining. It however reload them everytime you refresh. Just need to restart when there is a new file(which there was when I added the rerun command)

**Comment by ascobie** [comment]
sorry, i meant has the terminate string changed recently. 
anyway, restarted and it works fine, so will close.

**Comment by ascobie** [comment]
just saw your comment: "which there was when I added the rerun command"
