### ISSUE TITLE
Leaving the node file explorer with the stdout.txt file open appends content over and over

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1778]
Development 

While a task is running, click on the task and view the logs for it. If you leave it open the contents of the file keeps getting appended with the full contents of the file. So after being open for a minute or so i have 10 or 12 copies of the file contents in the file viewer. Seems the call to get the file content is every few seconds.

Seems that the refresh is appending the entire contents of the file, rather than just any new content.

Reproducible every time.

**Comment by timotheeguerin** [comment]
Seems like an issue with the tail

**Comment by timotheeguerin** [comment]
So this doesn't seem to happen if the file doesn't change in size. I guess this is when contentLenght of file changes it gets the full content instead of what's missing
