### ISSUE TITLE
Auto add file group output container

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1790]
Give user the ability to either add a default output container to use when submitting gallery template jobs, or be able to pass on in via ms-batchlabs:// route parameters from a plugin.

We pre-populate everything else when submitting a job from a plugin, but the user still has to always select the output file group. This tends to always be the same, so adding a default seems to be the right way to go.

**Comment by timotheeguerin** [comment]
You should change the links to `ms-batch-explorer` in your plugins.
