### ISSUE TITLE
2 different upload stats 

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1804]
Insider build: 0.18.4 - insider.183
Select container, drag and drop.
What's going on here? Why does one say 0% and the other say 58%??

![image](https://user-images.githubusercontent.com/10934358/49214036-9a570c80-f42a-11e8-983a-54749072f82d.png)

We also used to report when uploading a large file as users complained that it sat there for ages not doing anything. so i added an uploading large file specific message for when it was processing a large file.

**Comment by ascobie** [comment]
While we are at it. I can't seem to upload files from creating a new file group: 

message:"The specified blob or block content is invalid."
original:StorageError {name: "StorageError", message: "The specified blob or block content is invalid.↵Re…c9-875bb0000000↵Time:2018-11-29T10:02:18.9229691Z", code: "InvalidBlobOrBlock", statusCode: 400, requestId: "6f97a6e7-c01e-0031-01c9-875bb0000000", …}
requestId:"6f97a6e7-c01e-0031-01c9-875bb0000000"

**Comment by timotheeguerin** [comment]
Hhm, how did you get that(For both)? 
1. There is 2 different activities: Upload to file group with the form and the other is the drag and drop upload
2. Just created a file group fine

**Comment by ascobie** [comment]
it was with drag and drop into empty container, but i cannot seem to replicate it now. hrm.

**Comment by timotheeguerin** [comment]
Closed as this seems more of an temporary issue with Storage. Reopen if happens again
