### ISSUE TITLE
Drilldown into tasks no longer works when filtered

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/BatchExplorer#1843]
**Describe the bug**
After filtering the tasks list, clicking on a task no longer opens the details

**To Reproduce**
1. Go to 'Jobs'
2. Open up any job
3. Click in the Advanced Filter button
4. Select Active/Running
5. Click on a job that appears on the left

**Expected behavior**
The details of the task opens as it does when you click on one before filtering in step 3

**Actual behavior**
The task gets highlighted but not opened

**Version (please complete the following information):**
 - Verified on Windows
 - Works In version 0.18.4-stable.154, doesn't work in 0.19.0-stable.208

If you can't verify it then I'm happy to submit logs etc

**Comment by timotheeguerin** [comment]
Thanks for reporting I was able to reproduce the error. Will be part of a hot fix release. In the meantime you can close the advanced filter page by clicking on the filter again and the selected task should be behind it

**Comment by MatthewSteeples** [comment]
Thanks for the workaround

**Comment by timotheeguerin** [comment]
I am just deploying version 0.19.1 btw. Should be available ~10min.
