### ISSUE TITLE
Linux deb package not installable

### ISSUE THREAD

**Issue by sybrenstuvel** [Azure/BatchExplorer#1852]
**Describe the bug**

The [deb file](https://batchexplorer.azureedge.net/stable/0.19.1-stable.216/batch-explorer_0.19.1-stable.216_amd64.deb) depends on `gconfg-service` which does not exist on Ubuntu. My suspicion is that this is a typo, and that `gconf-service` (which does exist) should have been the dependency.

**To Reproduce**
1. Go to https://azure.github.io/BatchExplorer/
2. Click on Linux / deb
3. Attempt an install with `sudo dpkg -i batch-explorer_0.19.1-stable.216_amd64.deb`
4. See error:

```
dpkg: dependency problems prevent configuration of batch-explorer:
 batch-explorer depends on gconfg-service; however:
  Package gconfg-service is not installed.
```
5. Run `apt-cache search gconfg-service` and see that it doesn't exist.

**Expected behavior**

It should just install, or at least allow a subsequent `sudo apt-get install --fix-broken` install the dependencies and finish installing the package.

**Version (please complete the following information):**
 - OS: Kubuntu Linux 18.04 LTS
 - Version: batch-explorer_0.19.1-stable.216

**Comment by timotheeguerin** [comment]
Yes it is thanks for reporting

**Comment by timotheeguerin** [comment]
Could you confirm this fixes it for you https://azurebatch.visualstudio.com/_apis/resources/Containers/878733?itemPath=linux&$format=zip

**Comment by timotheeguerin** [comment]
Actually seems to be an issue with the version name used in PRs(Looks like underscore is not allowed)

**Comment by timotheeguerin** [comment]
This one worked fine for me. Let me know if it fixes the issue too https://dev.azure.com/azurebatch/BatchExplorer/_build/results?buildId=2789

**Comment by sybrenstuvel** [comment]
The `batch-explorer_0.19.1-stable.219_amd64.deb` file from build 2789 works fine for me. Thanks for fixing so quickly!
