### ISSUE TITLE
Batch Explorer not returning Subscriptions after login

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/BatchExplorer#1872]
Currently testing with an account that has access to 53 Azure Subs, when logging into batch explorer no subscriptions found and unable to filter in drop down menu. On many of the subs I have user access administrator RBAC. Is their a subscription call limit that loads only so many subscriptions into batch explorer ?

**Comment by timotheeguerin** [comment]
It shouldn't. Could you send the logs over to tiguerin@microsoft.com.
Is the UI just showing a blank list for the account list? Could you share screenshots too?

Thanks
