### ISSUE TITLE
Pool-picker shouldn't display AutoPools unless KeepAlive=true

### ISSUE THREAD

**Issue by davidkydd** [Azure/BatchExplorer#1905]
**Describe the bug**
AutoPools with the default value for AutoPoolSpecification.KeepAlive (false) can't be the target for jobs other than the job which they were created for, and shouldn't be displayed as a target in the pool-picker.

**Comment by timotheeguerin** [comment]
Will update that. Though I think it should still give the option to pick those pools(You never know). Maybe add a checkbox to show all pools

**Comment by davidkydd** [comment]
Initial issue description is incorrect - even with keepAlive =false you can run new jobs on it, so only issue is a potential race between the pool deleting and a new job being submitted to it. Like the idea of hidden by default with a "show all pools" checkbox.

**Comment by timotheeguerin** [comment]
This is a bit more tricky. From the pool itself you can't tell definitely if its an autopool. There are no properties that tell you that.
You'd have to cross reference with jobs

**Comment by timotheeguerin** [comment]
Will close this one as I don't think we can do this correctly. There might always be data a little out of sync which will make auto pool show up sometimes
