### ISSUE TITLE
CSS for favorite picker is broken

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1914]
Pinned favorite menu CSS is broken for the remove button. 

![image](https://user-images.githubusercontent.com/10934358/52816874-18ac7c00-3107-11e9-9f21-aca35ed36a41.png)

CSS for the "forms in progress" DDL is fine.

**Comment by timotheeguerin** [comment]
Oops is 5hat Master or stable?

**Comment by timotheeguerin** [comment]
Looks fine on master so will close it as fixed for the next release

**Comment by ascobie** [comment]
Still messed up on insider 300

![image](https://user-images.githubusercontent.com/10934358/54093804-695e7e80-4400-11e9-9ac3-89ae31ea7644.png)

**Comment by timotheeguerin** [comment]
Oh wonder if its because that text is wrapping

**Comment by timotheeguerin** [comment]
Actually thats weird seems to happen to the insider build but not dev 
![image](https://user-images.githubusercontent.com/1031227/54135790-b5e19400-43d7-11e9-913c-d89891c116d6.png)
