### ISSUE TITLE
Insider build unable to download (stable) update

### ISSUE THREAD

**Issue by mgroetan** [Azure/BatchExplorer#1919]
**Describe the bug**
Have an insider build installed (0.19.2-insider.262).
Lately, it has started reporting that it 's downloading the "0.19.2-stable.231" version, which is not an insider build.
In any case, it doesn't ever finish the download.

**To Reproduce**
1. Click on 'Profile' in the bottom left corner
2. See that the top line of the context menu says "Downloading update 0.19.2-stable.231"

**Expected behavior**
That either it doesn't try to download any stable version at all, or if meant to be like that, it should actually manage to download it and install it.

**Screenshots**
![batchexplorerendlesslydownloading](https://user-images.githubusercontent.com/9464822/53087721-1a5fb080-3508-11e9-8c85-d5858e2693e1.PNG)

**Logs(Click profile > View Logs > app.log, client.log)**
n/a

**Version (please complete the following information):**
 - OS: Windows
 - Version: 0.19.2-insider.262

**Comment by timotheeguerin** [comment]
Thanks for reporting, seems like there was still an issue with the auto update

**Comment by timotheeguerin** [comment]
Fixed in insider 272
