### ISSUE TITLE
Report progress from tree-view file download

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1925]
Have a file on VM that i wanted to download:

![image](https://user-images.githubusercontent.com/10934358/53203751-e9f64e80-368e-11e9-86e1-fc57e6982cc6.png)

It's quite large and so when i clicked download, and told it where to save the file to, the save dialog just closed and i got no further notifications at all until the file downloaded completed 4 minutes later. 

We should add this to the background task manager.

App version: 0.19.2-stable.231 (which is in itself strange as i was sure i had the insider build installed)

**Comment by timotheeguerin** [comment]
duplicate of #1381
