### ISSUE TITLE
Daily cost graph showing corrupt data

### ISSUE THREAD

**Issue by jussimattila** [Azure/BatchExplorer#1933]
**Describe the bug**
The daily cost graph is messed up. It used to look fine on my accounts until some time ago.

**To Reproduce**
1. Open Batch Explorer

**Expected behavior**
Graph should make sense.

**Screenshots**
![image](https://user-images.githubusercontent.com/8625258/53495856-6f239e00-3aa9-11e9-9bc0-0466df02d1d4.png)
![image](https://user-images.githubusercontent.com/8625258/53496006-caee2700-3aa9-11e9-8351-d3413ead14d0.png)

**Logs(Click profile > View Logs > app.log, client.log)**
If applicable please attach those log files

**Version (please complete the following information):**
 - OS: Windows
 - Version 0.19.2-stable.231 (latest at the time of writing)

**Comment by timotheeguerin** [comment]
Thanks for reporting this. When you say it used to work. Did you upgrade to a other version of Batch Explorer? Or just one day the data started showing weird values?

**Comment by timotheeguerin** [comment]
Looked into this and it seems the cost API is now returning prices per node in the pools in the accounts which make this graph show many data points in the same aggregate of time which seems to create this behavior. Will work on a fix.

**Comment by timotheeguerin** [comment]
Merged to master. Should be fixed and published to lastest insider build `.285` in ~30min.

**Comment by jussimattila** [comment]
Sorry for missing your questions earlier. Thanks for the fix!
