### ISSUE TITLE
Edit pool application packages not pre-populating existing

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1937]
Latest Insider build.

Wanting to edit application packages on an existing pool. When i click edit, the existing packages/version are not pre-populated in the list, though there are 2 entries there so it must know about them. Maybe the bindings need to be updated: 

![image](https://user-images.githubusercontent.com/10934358/53603097-5d5f0980-3c15-11e9-9237-cc2515b498ff.png)

**Comment by timotheeguerin** [comment]
Looks like a change detection issue. If you tab once or move focus it will show up
