### ISSUE TITLE
Absolute path in gallery 

### ISSUE THREAD

**Issue by matthew-rollitt** [Azure/BatchExplorer#1962]
Can we have the Absolute path in the gallery in the banner above the template window? It would make it easier to edit the template.

Also, I feel like the open in default application needs to open a deep copy not a temp file 

![image](https://user-images.githubusercontent.com/1754889/54239238-7d7cba00-457f-11e9-91ae-e1b47b79f2c2.png)

**Comment by timotheeguerin** [comment]
I already did those #1943. You can also update right in Batch Explorer now

![image](https://user-images.githubusercontent.com/1031227/54239680-202e2d80-44d9-11e9-9820-4c3678a444d7.png)
