### ISSUE TITLE
Start task resource files list does not show container sources

### ISSUE THREAD

**Issue by Porges** [Azure/BatchExplorer#1964]
The start task pane shows resource files, but only for blobs (`HttpUrl` in portal), not containers (`StorageContainerUrl`).

**Comment by timotheeguerin** [comment]
Are you on stable or insider?  Latest insider should have support

![image](https://user-images.githubusercontent.com/1031227/54319567-2db1e900-45a7-11e9-9a64-5bf6b2b760f5.png)

**Comment by Porges** [comment]
I must be on stable then 😁 thanks!
