### ISSUE TITLE
In the "Jobs" view, the default job sorting should be by creation date, not name

### ISSUE THREAD

**Issue by ant0nsc** [Azure/BatchExplorer#1966]
We use BatchExplorer in a pool that runs a very large number of jobs. When I open BatchExplorer and go to the Jobs view, I see the running job and all other jobs sorted by job name. What I'm usually interested in are (my or my team mates) recently completed or failed jobs. But there is no way for me to immediately see that. An issue has been file already as #1953 , but that appears to affect the job list, rather than the default view when I click "Jobs" in the lefthand navigation bar.

What I'd love to see: 
* When I am in the "Jobs" view, right after opening BatchLabs, I'd want the active jobs as the top, followed by terminating jobs, followed by other jobs in the order in which they were created (or finished), starting with the most recent ones
* In the "Advanced" filter for jobs, have controls for sorting by name and creation or termination date (presently only job state)

**Comment by timotheeguerin** [comment]
So the issue with sorting is that it has to be done client side. I don't think changing the default order(And then having to load all the jobs) would be a great experience. It would increase the loading time by quite a bit. Maybe a setting to choose the default sorting order?

**Comment by ant0nsc** [comment]
Agree that sorting should be on the client side. But I don't get your concern about default sorting order: Some sorting (probably on the client) is already in place, because my completed jobs show up in alphabetical order. Happy with a setting to choose default sorting order.
Can you clarify where I should click to sort? I'm on version 0.19.2-stable-231 (before your change), which appears to not have any sorting options for any of the properties of a job.

**Comment by timotheeguerin** [comment]
To sort right click on the list(Or table) then there is a sort by menu option. For the table you can also click on the header(Though this is limited to the visible columns)
![image](https://user-images.githubusercontent.com/1031227/54541399-184a0f80-4957-11e9-8e5c-cefab400728a.png)



So the sorting that you see is how the BatchService returns

**Comment by ant0nsc** [comment]
Turns out that I had not yet been on the version that I thought I was, there was no "Sort by" option yet. There is now, alongside lots of other nice improvements.
A flag to choose default sorting would be awesome, but I can work around with what's coming in the next stable release.

**Comment by timotheeguerin** [comment]
Will add the sort by completion time, for the flag it will probably not make it the next release. Will have to think a bit more about it.

**Comment by ant0nsc** [comment]
The flag is a nice-to-have, you probably have bigger fish to fry :-) The only thing I'd wish for is that the sorting order that I choose is memorized when I go out and back into the jobs list.

**Comment by timotheeguerin** [comment]
Hhm, that would be a good comprise to start with.
