### ISSUE TITLE
Recent templates from "my library" are a bit too long

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#1969]
Latest insider: 

recent template list for "my library" templates are a little too long. maybe truncate the start of them.

![image](https://user-images.githubusercontent.com/10934358/54575210-1156f600-4a58-11e9-96eb-e2352fbb4f36.png)

**Comment by ascobie** [comment]
also a "clear recent templates" option would be a good idea.

**Comment by timotheeguerin** [comment]
Made a separate issue for the clear recent templates #2013
