### ISSUE TITLE
UI Metrcis for pool's nodes

### ISSUE THREAD

**Issue by Gaploid** [Azure/BatchExplorer#1999]
**Describe the bug**

1. You can't select 24 hours from the dropdown menu to show graphs of metrics. Its automatically switched to 7 days.
2. Network graph seems broken it shows strange numbers in petabytes. 
![image](https://user-images.githubusercontent.com/6171245/55071321-5eab1700-5099-11e9-9fba-236da432dd11.png)

**To Reproduce**
1. Go to pool
2. Click on dropdown menu "last" for metrics and select 24 hours
3. See that it will be switched to 7 days.

**Comment by timotheeguerin** [comment]
Fixing the dropdown issue. Could you try to run those 2 query directly in application insights and see what it returns you:
Just replace "insights-windows" with the name of your pool
```
customMetrics
| where timestamp >= ago(1h)
| where cloud_RoleName == "insights-windows"
| where name == "Network read"
| extend mb = value / 1000000000
| summarize avg(mb) by bin(timestamp, 5min), cloud_RoleInstance
| render timechart 

customMetrics
| where timestamp >= ago(1h)
| where cloud_RoleName == "insights-windows"
| where name == "Network write"
| extend mb = value / 1000000000
| summarize avg(mb) by bin(timestamp, 5min), cloud_RoleInstance
| render timechart 
```

**Comment by Gaploid** [comment]
> ry to run those 2 query directly in application

Where exactly in-app insight can I execute these queries?

**Comment by timotheeguerin** [comment]
There is docs here https://github.com/Azure/batch-insights/wiki/Query-application-insights but basically go to the application insights in the azure portal and click on the analytics button

![image](https://user-images.githubusercontent.com/1031227/55120846-d0448e80-50b4-11e9-85f6-227a747e1798.png)

**Comment by timotheeguerin** [comment]
I'm going to close this as the first part is fixed and the second seems to be more of an issue with batch-insights.
