### ISSUE TITLE
Enable to retrieve Batch account with 2.0

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/BatchExplorer#2000]
**Describe the bug**
Sine Batch explorer 2.0 and with "pay as you go" subscription I am not able to retrieve the batch account in batch explorer, I am able to see the different subscriptions but no more.

It is working with Batch Lab and Batch Explorer 0.18.3-stable.99, can you help us fixing this issue ? or should I change something in my subscription ?

    {"0":{"details":[],"message":"","original":{"error":{"error":{"code":"DisallowedOperation","message":"The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."}},"headers":{"headers":{},"lazyInit":null,"lazyUpdate":null,"normalizedNames":{}},"message":"Http failure response for https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01: 400 OK","name":"HttpErrorResponse","ok":false,"status":400,"statusText":"OK","url":"https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01"},"requestId":"3662566a-3338-4d98-8ebd-3e291cdd6c04","status":400,"statusText":"OK","timestamp":"2019-03-27T14:45:35.000Z"},"level":"error","message":"Error loading accounts","timestamp":"2019-03-27T14:45:36.819Z"}

{"0":"400 - OK - ","level":"error","message":"[BL] Uncaught exception:","timestamp":"2019-03-27T14:45:36.823Z"}

{"0":{"details":[],"message":"","original":{"error":{"error":{"code":"DisallowedOperation","message":"The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."}},"headers":{"headers":{},"lazyInit":null,"lazyUpdate":null,"normalizedNames":{}},"message":"Http failure response for https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01: 400 OK","name":"HttpErrorResponse","ok":false,"status":400,"statusText":"OK","url":"https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01"},"requestId":"XXX","status":400,"statusText":"OK","timestamp":"2019-03-27T14:45:38.000Z"},"level":"error","message":"Error loading accounts","timestamp":"2019-03-27T14:45:40.198Z"}

{"0":{"details":[],"message":"","original":{"error":{"error":{"code":"DisallowedOperation","message":"The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."}},"headers":{"headers":{},"lazyInit":null,"lazyUpdate":null,"normalizedNames":{}},"message":"Http failure response for https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01: 400 OK","name":"HttpErrorResponse","ok":false,"status":400,"statusText":"OK","url":"https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01"},"requestId":"XXX","status":400,"statusText":"OK","timestamp":"2019-03-27T14:45:41.000Z"},"level":"error","message":"Error loading accounts","timestamp":"2019-03-27T14:45:42.104Z"}

{"0":{"details":[],"message":"","original":{"error":{"error":{"code":"DisallowedOperation","message":"The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription."}},"headers":{"headers":{},"lazyInit":null,"lazyUpdate":null,"normalizedNames":{}},"message":"Http failure response for https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01: 400 OK","name":"HttpErrorResponse","ok":false,"status":400,"statusText":"OK","url":"https://management.azure.com/subscriptions/subscriptionID/providers/Microsoft.Batch/batchAccounts?api-version=2018-12-01"},"requestId":"XXX","status":400,"statusText":"OK","timestamp":"2019-03-27T14:45:45.000Z"},"level":"error","message":"Error loading accounts","timestamp":"2019-03-27T14:45:45.842Z"}
`

**Comment by timotheeguerin** [comment]
Looks like an issue with the subscription that the server doesn't like. Could you double check it was working in 0.19.2 
https://batchexplorer.blob.core.windows.net/stable/0.19.2-stable.231/BatchExplorer-0.19.2-stable.231-win.zip

**Comment by AlexandreJean** [comment]
It works with the 0.19.2-stable.231 version !

**Comment by timotheeguerin** [comment]
That is very weird. Maybe something to do with the API version. Could you check in your subscription in the Azure portal the `Microsoft.Batch` provider is registered

![image](https://user-images.githubusercontent.com/1031227/55173977-df215480-5139-11e9-8783-78f6fe4b60d3.png)

**Comment by AlexandreJean** [comment]
Hello,
It was not regitered for the line Microsoft.BatchAI, after click on "Register", it is nos on Registered status but we still have the issue.
Thanks

**Comment by timotheeguerin** [comment]
Thanks for checking this, BatchAI should be unrelated. Did browsing the batch account in the azure portal worked?

**Comment by timotheeguerin** [comment]
So I actually think I know the change in 2.0 that triggered this issue. We changed how we list batch accounts to call the /batchaccounts api of the Microsoft.Batch provider instead of using the general list resource api. This allows to have more data returned. Somehow your subscription has some issue with this API. Could you also try to unregister and register again?

**Comment by timotheeguerin** [comment]
Sorry, one additional thing. Could you go to the docs website for this api and click the try it button to see if the api returns you the same result

https://docs.microsoft.com/en-us/rest/api/batchmanagement/batchaccount/list

![image](https://user-images.githubusercontent.com/1031227/55246422-69cd8680-5202-11e9-8346-f31dd35bbbff.png)

![image](https://user-images.githubusercontent.com/1031227/55246451-7651df00-5202-11e9-9a1d-12073ef0b1b1.png)

**Comment by AlexandreJean** [comment]
Hello,

We are able to have the list of the batch account with the try it.

Thanks

**Comment by timotheeguerin** [comment]
And it still doesn't work in Batch Explorer 2.0? This is very weird.

**Comment by AlexandreJean** [comment]
Hello, Sounds good now !

**Comment by timotheeguerin** [comment]
Great to hear! any idea what might have fixed it?
