### ISSUE TITLE
Show number of jobs in status bar

### ISSUE THREAD

**Issue by raghutillu** [Azure/BatchExplorer#2002]
There is no indication anywhere in the UI for the number of jobs in a pool if the list grows really long.

![image](https://user-images.githubusercontent.com/13340619/55098804-ca7e8700-507b-11e9-9e33-6bb41cc4f32e.png)

**Comment by timotheeguerin** [comment]
Should show in the job quota under. Seems like its 0/0 for you can you share logs? `ctrl+shift+i`

**Comment by bgklein** [comment]
This is believed to be since @raghutillu was a local batch account (no arm capability). resolving.
