### ISSUE TITLE
Clone pool not setting app package name

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchExplorer#2019]
Insider latest

Select a pool with application packages and clone it. The application package version is pre-selected, but not the package itself.

![image](https://user-images.githubusercontent.com/10934358/56101534-cce84880-5f78-11e9-9415-b3c374b53520.png)

It's in the list, its just not being selected: 

![image](https://user-images.githubusercontent.com/10934358/56101547-f5704280-5f78-11e9-84d7-44eb5b9a5068.png)

probably a casing issue again:

![image](https://user-images.githubusercontent.com/10934358/56101570-2c465880-5f79-11e9-8904-87482007efb6.png)

**Comment by timotheeguerin** [comment]
Yeah looks like a casing issue, happens when editing the app packages as well
