### ISSUE TITLE
No pool in job creation

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/BatchExplorer#2029]
**Describe the bug**
When I want to create a Job Azure Batch Explorer is not able to see any pool created,

**Expected behavior**
Before I was able to select one of the pool created 

**Screenshots**
![Create_Job](https://user-images.githubusercontent.com/41644632/56657253-da4bb400-6697-11e9-9040-5df0e41ef9a3.png)
![2_pool](https://user-images.githubusercontent.com/41644632/56657392-2991e480-6698-11e9-96a4-e61606d59889.png)

**Version (please complete the following information):**
 - OS:  WINDOWS
 - Version 10 1809

**Comment by timotheeguerin** [comment]
Fixed, version `2.1.1` should be available within 10 minutes.
