### ISSUE TITLE
"Connect to node" with admin flag does not have admin rights

### ISSUE THREAD

**Issue by bojordan** [Azure/BatchExplorer#2033]
Creating a new user with Admin flag in Connect to Node dialog doesn't set the user as admin.

Aware of #572 but this appears in latest version.

![image](https://user-images.githubusercontent.com/626103/57382536-fce2d000-7161-11e9-9a24-50d2b2b6976d.png)

 - OS: Windows
 - Version: 2.1.1-stable.344

**Comment by timotheeguerin** [comment]
Thanks for reporting this, sounds like a regression bug. I was able to repro
