### ISSUE TITLE
Runtime sort for tasks incorrect for incomplete tasks

### ISSUE THREAD

**Issue by bojordan** [Azure/BatchExplorer#2034]
Client-side sorting of tasks works, but sorting by the "Runtime" column does not sort properly for tasks that are not completed.

See screenshot:
![image](https://user-images.githubusercontent.com/626103/57382965-cbb6cf80-7162-11e9-8c58-c96844fedd4b.png)

 - OS: Windows
 - Version 2.1.1-stable.344

**Comment by timotheeguerin** [comment]
This was fixed in latest stable
