### ISSUE TITLE
Unable to filter for "offline" nodes

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#2069]
**Describe the bug**
Unable to filter nodes in "offline" state

**To Reproduce**
1. Go to a pool
2. Wait for the heatmap to load
3. See 1 or more nodes in "offline" state
4. Go to Nodes tab
5. Click toggle advanced filter
6. See no tickbox for "offline" state

**Expected behavior**
Tickbox for "offline" state

**Version (please complete the following information):**
 - OS: Windows
 - Version: 2.2.0-stable.368

**Comment by bgklein** [comment]
This should get added if possible. Depending on the complexity of what you are aiming to filter, you can   use the graphs page filter functionality until this is fixed:
![image](https://user-images.githubusercontent.com/18502617/64029870-46cd3880-cafa-11e9-87dc-38d3c7112b04.png)

**Comment by bgklein** [comment]
This should be fixed in the latest insider build (and will be fixed in next stable release)

**Comment by chrisalexander** [comment]
Thank you for the workaround and quick fix :)
