### ISSUE TITLE
Task filter not applied when refresh clicked

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#2072]
**Describe the bug**
Task filter not applied when refresh clicked

**To Reproduce**
1. Go to a job
2. Click the filter button at the top of the list of tasks
3. Apply a filter e.g. running
4. Click refresh button at top of task list

Sorry this one has been irritating me for a while but have only got round to reporting now.

**Expected behavior**
List refreshes, showing currently running tasks

**Actual results**
List refreshes, showing all tasks

**Workaround**
Untick running filter, retick running filter

**Version (please complete the following information):**
 - OS: Windows
 - Version 2.2.0-stable.368

**Comment by bgklein** [comment]
Thanks for reporting this! Considering we aren't clearing the filters on refresh, the expected behavior you described makes sense.

**Comment by chrisalexander** [comment]
Thank you very much for sorting :-) This a useful tool and it's great to have the little niggles sorted.

**Comment by chrisalexander** [comment]
OMG this is so useful, has saved me today
