### ISSUE TITLE
Batch Explorer shows failed tasks in job, no trace of failed jobs

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#2081]
**Describe the bug**
On the batch explorer pie chart for task statuses within a job, we had failed tasks shown. However neither I nor Azure Support could find any trace of any failed tasks within that job.

**To Reproduce**
Sorry this is sporadically reproducible.
Please refer to Azure ticket 119090622001703 for further details.

**Comment by bgklein** [comment]
It seems that BatchExplorer was functioning correctly in this case.  You should receive a response to the support ticket which explains the Service behavior which can temporarily lead to this state.

**Comment by chrisalexander** [comment]
Thanks have received reply and will work with them on the underlying issue. Apologies they directed me to this where the issue was internal.

**Comment by karlti** [comment]
Yes, sorry for the noise…..
I just confirmed that the tasks were rescheduled and eventually all were processed successfully.
/*Karl
