### ISSUE TITLE
Unable to filter for failed tasks

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchExplorer#2084]
**Describe the bug**
When there is a non-zero "failed" task count on the job pie chart, it is difficult to discover these tasks.

**To Reproduce**
1. Go to a job with failed tasks
2. Click on the filter button

**Expected behavior**
Tickbox labelled "Failed" which shows tasks that have contributed towards this failed task count. Current workaround is to tick complete and exclude 0 exit codes, however that does not show tasks which have been failed and will be retried.

**Version (please complete the following information):**
 - OS: Windows
 - Version 2.3.1-stable.378

**Comment by bgklein** [comment]
Thanks for submitting this! I believe we have had this request before at some point (especially since in rare cases a task can fail with a zero exit code).

**Comment by chrisalexander** [comment]
Would it be possible to expedite this feature please? It has had me over again today. Thanks

**Comment by bgklein** [comment]
@chrisalexander I'll look at getting this into the insider build either today or tomorrow.

**Comment by bgklein** [comment]
This should be available on the insider build shortly and will be included in our next release
