### ISSUE TITLE
Python Backend disconnected

### ISSUE THREAD

**Issue by franckhlmartin** [Azure/BatchExplorer#2116]
**Describe the bug**
At start the screen shows in bottom left "Python Backend disconnected"

Restarting it does not work

"Run" or" Run and close" buttons, spin without anything happening.

**To Reproduce**
1 ) Launch

**Expected behavior**

**Screenshots**

**Logs(Click profile > View Logs > app.log, client.log)**
{"message":"Python path is: '/Applications/BatchExplorer.app/Contents/Resources/python-rpc/main', Args: 45032","level":"info","timestamp":"2019-11-03T03:54:20.325Z"}
{"message":"Python Rpc server started!","level":"info","timestamp":"2019-11-03T03:54:20.332Z"}
{"level":"error","message":"Python Rpc server has exited unexpectedly with code! null","timestamp":"2019-11-03T03:54:20.334Z"}

{"level":"info","message":"Websocket connection closed. Retrying to connect in 131072s","timestamp":"2019-11-03T03:54:58.134Z"}
{"level":"info","message":"Websocket connection closed. Retrying to connect in 262144s","timestamp":"2019-11-03T03:55:29.172Z"}
{"level":"info","message":"Websocket connection closed. Retrying to connect in 524288s","timestamp":"2019-11-03T03:56:37.413Z"}

info: ========================= STARTING PYTHON RPC SERVER PROCESS =========================
info: [58814] Failed to execute script main

$ /Applications/BatchExplorer.app/Contents/Resources/python-rpc/main 
Adding new proc create-file-group
Adding new proc submit-ncj-job
Adding new proc create-ncj-pool
Adding new proc expand-ncj-pool
Adding new proc foo
Adding new proc simple
Starting websocket server...
Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "main.py", line 27, in run
  File "server/websocket_server.py", line 25, in run_forever
  File "asyncio/base_events.py", line 468, in run_until_complete
  File "asyncio/tasks.py", line 537, in _wrap_awaitable
  File "site-packages/websockets/py35/server.py", line 13, in __await_impl__
  File "asyncio/base_events.py", line 1015, in create_server
  File "asyncio/base_events.py", line 963, in _create_server_getaddrinfo
  File "concurrent/futures/thread.py", line 56, in run
  File "socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
[58606] Failed to execute script main

**Version (please complete the following information):**
 - OS: OSX
 - Version 10.14.6

**Comment by bgklein** [comment]
@franckhlmartin What version of BatchExplorer are you running? This should be fixed in the latest release. You can check by right clicking Profile -> About

**Comment by franckhlmartin** [comment]
@bgklein : I use Version: 2.4.1-insider.393 but I was with the stable latest before I tried with this version too...

**Comment by bgklein** [comment]
@franckhlmartin Are you behind a VPN/Proxy? It seems like the underlying socket module is having issues getting the servname.

**Comment by franckhlmartin** [comment]
@bgklein, I'm not, straight internet connection from Comcast. May be there is some firewall somewhere... if you give me what I should connect to, then I could test the connection with nc or tools like this? I could check the code to, to better understand, but if you have the info, faster.

**Comment by bgklein** [comment]
the PythonServer is started on localhost port 8765.

**Comment by bgklein** [comment]
The 'server' is a local server which runs on localhost. The client port is dynamically assigned on start up (first available), and the server port should be 8765

**Comment by franckhlmartin** [comment]
ok installed python3 and did some of the examples here:
https://websockets.readthedocs.io/en/stable/intro.html
to realize my /etc/hosts file is empty... fixed it, it works now...
