### ISSUE TITLE
SSH is not connecting to Pool Node

### ISSUE THREAD

**Issue by megel** [Azure/BatchExplorer#2130]
The SSH does not connect to my pool node and stays in the waiting screen:
![image](https://user-images.githubusercontent.com/15800069/69611792-db2e3500-102e-11ea-9c11-8065c1a2a4f2.png)

Pool Image:
![image](https://user-images.githubusercontent.com/15800069/69611901-09137980-102f-11ea-9de6-d068db99107b.png)

Batch Explorer:
Current Version (don't know where the Version Information can be found)

**Comment by bgklein** [comment]
I believe this has been fixed by #2120 , so switching to the insider build should resolve the issue until we do our next release (Profile -> settings -> Update Channel [change to insider])

**Comment by megel** [comment]
I'll check tomorrow.
