### ISSUE TITLE
Jobs View: separate active from completed

### ISSUE THREAD

**Issue by rfernand2** [Azure/BatchExplorer#2145]
After running many jobs (> 25), it becomes difficult to find and focus on the active jobs.  It would be great if the Jobs View panel could divide these up visually (for example, use "Active" and "Completed" tabs at the top of the panel).

Currently, I find myself always deleting the completed jobs so I can focus on the active ones.  This shouldn't be necessary, and there may be reasons to keep completed jobs in the future.

**Comment by bgklein** [comment]
A filter can be added by toggling the advanced filter options 
![image](https://user-images.githubusercontent.com/18502617/71829813-49b4d880-305a-11ea-9927-9e4aebbf3bf9.png)
![image](https://user-images.githubusercontent.com/18502617/71829828-51747d00-305a-11ea-812e-14f5103c5813.png)
