### ISSUE TITLE
Issues with Authentication with Multi-Tenant configured accounts

### ISSUE THREAD

**Issue by trindels** [Azure/BatchExplorer#2161]
I am unable to authenticate into Azure Batch Explorer.  My Azure AD account is linked as a guest account to multiple Microsoft Tenants, due to the nature of working in the service provider field.  Several of these clients have either marked my guest account as disabled, or have advanced conditional access policy configurations that are preventing authentication of my account.  

Once my authentication hits only one of these client tenants, I am unable to gain access to using Batch Explorer.  If I try to cancel out of the authentication, Batch Explorer closes immediately.

I am requesting either a bug fix or a feature enhancement.
- Bug Fix:  Error handling to be added to work with authentication failure of multiple tenant users
- Feature Request:  Enhanced AAD Tenant selection capabilities after initial authentication

**Comment by bgklein** [comment]
Thank you for reporting this. @cRui861 was looking into this earlier in the week, with regards to a possible fix.

**Comment by lmiroslaw** [comment]
I also can't authenticate. After I specify my login and domain Azure Batch just hangs waiting for user input with a note "Prompting for user input".

**Comment by KrisJanssen** [comment]
I am also impacted by this: it is a significant showstopper for us. Is there an ETA for fix or a viable workaround?

**Comment by louisdegaste** [comment]
I also have the exact same issue. Also when unintastalling and reinstalling batch explorer, it still forces me to sign in with the undesired tenant.

**Comment by louisdegaste** [comment]
Deleting the cache files in  /AppData (which stayed despite the uninstallation) did the trick though

**Comment by halwebguy** [comment]
Same issue...it's automatically selecting the wrong tenant for me to 2FA. I can't change which tenant I'd like to use.

**Comment by lyulyok** [comment]
Same here. Any way to specify the one tenant that would be relevant when using Batch Explorer rather than requiring it to login everywhere?

**Comment by miguelhasse** [comment]
> I also can't authenticate. After I specify my login and domain Azure Batch just hangs waiting for user input with a note "Prompting for user input".

Same thing happens to me :(

**Comment by soulsf** [comment]
@cRui861  any news on this?

**Comment by cRui861** [comment]
Adding @gingi for further updates on this issue.

**Comment by gingi** [comment]
We are working on a fix for this, and should have it available on the Insider build by by early next week.

**Comment by sfarhand** [comment]
@gingi any updates on the progress? A couple of our team members were not been able to use Batch service effectively due of this issue.

**Comment by gingi** [comment]
We ran into a bit of a snag but pushing through this feature. It should be available shortly.

**Comment by gingi** [comment]
The [latest insider build](https://azure.github.io/BatchExplorer/insider.html) now includes a fix for this. Stable release expected in January.
