### ISSUE TITLE
BatchExplorer does not work with Okta

### ISSUE THREAD

**Issue by jpapp05** [Azure/BatchExplorer#2165]
Our Azure access is protected by Okta and requires the selection of a certificate.  This works fine with web access/browsers, the Microsoft Teams client, and Office365, etc., but fails in BatchExplorer.   You can find more about this here:

https://help.okta.com/en/prod/Content/Topics/Mobile/Okta_Mobile_Device_Trust_Windows-desktop.htm

I think the issue is that the prompt for the certificate that is normally presented is blocked or canceled.  Fixing this would allow tools such as these to work in more corporate environments.   

Here is what the cert selector looks like when logging into Teams:

![image](https://user-images.githubusercontent.com/39598625/79313683-8bed8180-7eb5-11ea-8937-eb9c01e0a927.png)

It looks different in Edge Chromium.

I'm going to try setting my group policy to auto choose the cert for both IE and Chromium to see if that helps.

Any other suggestions welcomed.

Thanks,
James

**Comment by bgklein** [comment]
For 2FA scenario's the workflow should be something along the lines of:
![image](https://user-images.githubusercontent.com/18502617/79361862-b6156280-7efa-11ea-89d1-e16af8fdb68c.png)
=>
![image](https://user-images.githubusercontent.com/18502617/79361920-c9283280-7efa-11ea-9b3b-23ab6075dbfb.png (here you can select 2FA option)

Which exact step is failing for you?

Ultimately our behavior is creating a new chromium window which points to the oauth endpoint of the tenant authorize URL.

**Comment by jpapp05** [comment]
This part works fine.  We are correctly redirected to the needed pages within the app.  However, the very last bit requires a certificate exchange for the Windows cert store.    The web-browser (in my case), needs to pop up a dialog to select the correct cert and to approve it.   When using Batch Explorer the dialog/popup is never shown,  and our authentication fails as if I canceled the request. 

If I login through a browser or use other similar web-based apps like Teams and others it works fine. 

This cert popup is part of  the browser and is not a web page, it is similar to the dialogs you get when the browser presents the user for Window account credentials. 

Here is the prompt Edge Chromium shows me when logging into our Azure subscription.

![image](https://user-images.githubusercontent.com/39598625/79371752-b8cb8400-7f09-11ea-81f6-57c710c456bd.png)

For whatever reason the browser in Batch Explorer never shows me this popup and therefore I'm unable to use it in our corporate environment.

**Comment by jpapp05** [comment]
Note sure if this helps but the desktop Azure apps for the Portal and Storage Explorer do not have this issue and work fine in our environment.

**Comment by bgklein** [comment]
We will likely need to look into what StorageExplorer is doing as I believe they are also an Electron native application.

**Comment by james-papp** [comment]
Hi all,

I have a bit of addition information that my be helpful with this issue.

The problem may be the User-Agent sent with the requests, which seem to indicate itself as BatchExplorer.

If I take your URLs (during auth) and paste them into a web-browser I get further; though, I still hit an error from our company asking if I'm using an authorized version of Azure CLI...  It seems to be confused about the host making the request...

I then tried installing the Azure CLI and it seems to work great; though, it just launches a browser to do the login bits which always worked.  

Is there any way to reset or override the User-Agent string to match a known browser (e.g. Edge Chromium)?  If so I can at least do a bit more testing....

As mentioned previously, the Azure websites, Azure Portal, Storage Explorer (and now the Azure CLI) all work without issue.  I'm just having difficulties with BatchExplorer.

**Comment by jpapp05** [comment]
Ugh... Sorry, posted my response with my home account.  I seem to be joggling too many accounts these days; I'm sure an artifact of working from home for too long.

**Comment by bgklein** [comment]
I'll try to get you a build of #2184 Either tonight or Tuesday, which should conform to normal mozilla/5.0 user agent precursor which should be enough from my looks at okta documentation describing what you explain. The user agent including the application is a large help when debugging issues, so ideally we don't have to remove that part and we were just missing the part that said we support Mozilla/5.0

**Comment by bgklein** [comment]
Sorry for the delay, trying to work through an issue in the CI login tests which is blocking a build

**Comment by jpapp05** [comment]
No worries.  Just let me know when it is ready and where to get it; I'm happy to test.
