### ISSUE TITLE
BatchExplorer will not run under Mac OS-X 10.15.4

### ISSUE THREAD

**Issue by TalboTekLtd** [Azure/BatchExplorer#2182]
BatchExplorer-2.7.0-stable.418.dmg will not run as an application because

"Apple cannot check it for malicious software"

See attached screenshot
<img width="418" alt="Screenshot 2020-05-18 at 13 17 11" src="https://user-images.githubusercontent.com/62891449/82212611-b8f4e000-990a-11ea-8f89-acb26178dea6.png">

**Comment by dpwatrous** [comment]
I'm seeing the same issue on 10.15.6 - we need to enable notarization on the .dmg. We'll look into this.

This isn't a great answer, but there is a work-around to disable Gatekeeper in the meantime: run `sudo spctl --master-disable` and in System Preferences under Security > General, enable "All apps" to run.

**Comment by dpwatrous** [comment]
A better work-around until we can get the app notarized: Right click (or control-click) on the BatchExplorer application and select open. This will still display a warning, but you should be able to bypass it and run the app.

**Comment by TalboTekLtd** [comment]
Thanks 

 

FYI, this process of right click – open , seems to require several attempts to be recognised. First attempt you just come up with the security violation again, second attempt OS-X shows you an “open” button.

NB, upgraded to 2.7.0 build 428

 

I am possibly seeing some issues with creating a batch account, so might raise another ticket later.

 

Regards, Keith

**Comment by Spillmaker** [comment]
This is still an issue. The error-message has however changed to a more generic one.

Right-clicking and opening does not work for me.

<img width="433" alt="bilde" src="https://user-images.githubusercontent.com/696120/92312684-53b12180-efc3-11ea-895c-d86f9a191858.png">

**Comment by oWretch** [comment]
I had issues with trying to get BatchExplorer to launch on a M1 Mac with Big Sur. I had to run the following command in Terminal to allow it to open:
```bash
sudo spctl --add /Applications/BatchExplorer.app
sudo xattr -d com.apple.quarantine /Applications/BatchExplorer.app
```
