### ISSUE TITLE
no pool name displayed in job edit

### ISSUE THREAD

**Issue by xavbx33** [Azure/BatchExplorer#2185]
**Describe the bug**
Since the 2.4.0 the Pool selection list from Job edition does not display the name of the pool.

**To Reproduce**
1. Go to Job list
2. Click on an existing job
3. Click on disable in button bar - Wait until the job status go from "disabling" to "disabled"
4. Click on "Edit" in the button bar
5. Scroll to "2. Pool selection"
4. See the list of existing job displayed without name

**Expected behavior**
In 2.3.1-stable.378 we had the full name of pools displayed properly

**Screenshots**
![image](https://user-images.githubusercontent.com/31845104/83504850-4c124600-a4c5-11ea-8a49-856930f21f47.png)
Whereas in 2.3.1 we had:
![image](https://user-images.githubusercontent.com/31845104/83506418-7402a900-a4c7-11ea-99f2-d72225580fb9.png)

**Logs(Click profile > View Logs > app.log, client.log)**
[app.log.2020-06-02.txt](https://github.com/Azure/BatchExplorer/files/4716245/app.log.2020-06-02.txt)

**Version (please complete the following information):**
 - OS: Windows
 - Version 10.1809

**Comment by sylr** [comment]
Could someone take a look ? @cRui861  ?

**Comment by xavbx33** [comment]
Just to confirm that the issue is still present with the Version 2.11.0-stable.541

**Comment by xavbx33** [comment]
Issue seems to be fixed on version 2.14.2-stable.628
