### ISSUE TITLE
Will not show me any of my subscriptions or Batch accounts

### ISSUE THREAD

**Issue by grandparoach** [Azure/BatchExplorer#2200]
**Describe the bug**
After logging in with my microsoft.com credentials, it will not show me any subscriptions or Batch accounts. 

**To Reproduce**
1. Log in with microsoft.com credentials
2. Under BATCH ACCOUNTS in the top left corner, the first dialog box says "Subscriptions"
3. When I click on the drop down arrow, it changes to "Filter items..." and below that all it shows is "Unselect all", and underneath that it says "No options available"

**Expected behavior**
I would expect it to show a list of the subscriptions, and under each one, the corresponding Batch accounts

**Screenshots**
![image](https://user-images.githubusercontent.com/16225336/87611569-39db1880-c6bd-11ea-84aa-1cef700969bd.png)

**Logs(Click profile > View Logs > app.log, client.log)**
If applicable please attach those log files

**Version (please complete the following information):**
 - OS: Windows 10
 - Version 2.7.0-stable.418-win

**Comment by cRui861** [comment]
You will need at least one Batch Account on the subscription (you can create one through the Azure Portal https://azure.microsoft.com/en-us/features/azure-portal/) or have the subscription registered with the Batch resource provider for the subscription and Batch Accounts to be displayed.

**Comment by grandparoach** [comment]
Thanks for the speedy response.  I have several Batch accounts already defined in one subscription, and that credential gives me access to multiple subscriptions which also have multiple Batch accounts in them.  Your response says "or have the subscription registered with the Batch resource provider"  I will try that next.

**Comment by grandparoach** [comment]
I made sure that my subscription was registered with the Microsoft.Batch resource provider, but that didn't make any difference.  Batch Explorer still indicates "No account selected!" in the bottom left corner.  When I click on the "Create a new batch account" option, the Subscription dialog box shows "no options available"

**Comment by grandparoach** [comment]
I logged in with my hotmail credentials, and did not experience the same problem.  And I had a co-worker log in with his credentials and everything worked.  So, the problem seems to be with my microsoft.com credentials.  I would appreciate any suggestions about where I can turn to get that resolved.

**Comment by cRui861** [comment]
Debugged the issue offline. 

Batch Explorer was expecting at least read access to a tenant ID. Resolved by getting subscription removed from that particular directory.
