### ISSUE TITLE
Maya 2020

### ISSUE THREAD

**Issue by BrianHanke** [Azure/BatchExplorer#2234]
Will Maya 2020/Arnold be available in Batch Explorer/Azure at some point? Thank you!

**Comment by matthew-rollitt** [comment]
Hi Brian, sorry for the delay we have recently updated our templates and our rendering image now supports Maya 2020 with Arnold. To see the full list of supported software see https://docs.microsoft.com/en-us/azure/batch/batch-rendering-applications#applications-on-latest-windows-server-rendering-image
