### ISSUE TITLE
Image preview is broken in Task Output

### ISSUE THREAD

**Issue by cRui861** [Azure/BatchExplorer#2274]
**Describe the bug**
The download button for a file on Task Outputs tab doesn’t seem to work – animates, but no download – have to use the right-click download on a file. JPG/PNG rarely display, but do sometimes.

**To Reproduce**
1. Go to the jobs blade
2. Click on a job and then select a task
3. Under the task outputs section, there should be an image file next to the `stdout.txt` and `stderr.txt`
4. Click the download button and it should load but the download never occurs

**Expected behavior**
Clicking the download button on the file on Task Outputs should produce a downloaded version of that file.

**Screenshots**
![image](https://user-images.githubusercontent.com/16728220/106825168-22538500-6639-11eb-9325-2455c45ff9f7.png)

**Version (please complete the following information):**
 - OS: Window

**Comment by gingi** [comment]
The download button error is different from the image thumbnail. The download button error is tracked with #2272 (and addressed by #2275). This issue will track the image thumbnail error.
