### ISSUE TITLE
Remove Nodes API call within batch explorer

### ISSUE THREAD

**Issue by abnagava** [Azure/BatchExplorer#2301]
**Is your feature request related to a problem? Please describe.**
I would like to have a feature built within the batch explorer to remove specific nodes from the pool. This is to remove any unusable nodes from the pool or preserve just them for troubleshooting instead of running the entire pool

**Describe the solution you'd like**
Similar to resize, clone, and delete operations at a pool level, having a feature to ask which pools to delete would be helpful rather than using another client to call below API.
https://docs.microsoft.com/en-us/rest/api/batchservice/pool/removenodes

**Comment by dpwatrous** [comment]
Hi @abnagava,

We do expose the remove nodes API, though in the Batch Explorer UI it's labeled "delete".

Select a pool, then on the "Nodes" tab, select the node you would like to remove. This will bring up the node detail view with a garbage can icon you can use to remove that node. The side bar will also switch to showing the nodes in a list, which you can use to multi-select and delete (using ctrl-click and/or shift-click).

See the screenshots below:

Node list on the pool:
![image](https://user-images.githubusercontent.com/509299/118689806-64ae6580-b7d5-11eb-8157-66a6a847495e.png)

Node detail view:
![image](https://user-images.githubusercontent.com/509299/118689853-71cb5480-b7d5-11eb-8d74-c3c9840bcd7c.png)
