### ISSUE TITLE
Freezing when refreshing Batch Explorer

### ISSUE THREAD

**Issue by cRui861** [Azure/BatchExplorer#2306]
**Describe the bug**
Batch Explorer freezes sometimes when refreshing the application (ctrl + r). It takes multiple attempts of refreshing or just restarting the application for the freezing to go away.

**Expected behavior**
Batch Explorer should successfully refresh the application without freezing.

**Screenshots**
![image](https://user-images.githubusercontent.com/16728220/114949794-9a42e600-9e06-11eb-8e68-aba6e0726038.png)

**Version (please complete the following information):**
 - OS: Windows and Mac

**Comment by dpwatrous** [comment]
@cRui861 is this still happening? I know we fixed an issue with the dev tools breaking on error while invisible, and another that was a bug in the chokidar library which causes intermittent freezing.

**Comment by cRui861** [comment]
Yeah I haven't attempted a fix yet for this.

**Comment by dpwatrous** [comment]
Closing this as I believe it was an issue with a hidden devtool pane with a breakpoint enabled. (Feel free to reopen if I'm misremembering here)
