### ISSUE TITLE
Unable to login with my personal account. 

### ISSUE THREAD

**Issue by rawwar** [Azure/BatchExplorer#2344]
I am trying to log in with my personal account. Which is a @live.com email. But, i keep getting the following error - 
"You can't sign in here with a personal account. Use your work or school account instead." How do i log in with  my personal account?

**Comment by dpwatrous** [comment]
Thanks for the report - this looks like a regression when we switched the authentication library to MSAL. We'll look into it!

**Comment by zerweck** [comment]
Any Update? We have the same problem and can't use Batch Explorer for a while now.

**Comment by rawwar** [comment]
I created a temporary user using AAD. That also creates an email that ends with `onmicrosoft.com`. You can log in using this email id. But, even I am waiting for a fix.

**Comment by dpwatrous** [comment]
Not much of an update, but I believe this has to do with the initial scope of management.azure.com that we're using to query tenants, which only supports AAD accounts. Still trying to figure out the right fix, however.

**Comment by dpwatrous** [comment]
After a lot of reading, it looks like it's a behavior change with the v2 auth endpoints we're using. Switching to using the /organizations tenant instead of /common seems to have done the trick.

I'll put a PR up and we'll get this into the insiders build right away. Let us know if that solves the issue for you!

**Comment by dpwatrous** [comment]
This should be live in the latest insiders build now. We'll try to get this released to stable next week.

**Comment by zerweck** [comment]
> After a lot of reading, it looks like it's a behavior change with the v2 auth endpoints we're using. Switching to using the /organizations tenant instead of /common seems to have done the trick.
> 
> I'll put a PR up and we'll get this into the insiders build right away. Let us know if that solves the issue for you!

Since you asked to let you know: Yes, this solved it for us. Thank you!

**Comment by dpwatrous** [comment]
Glad to hear it!
