### ISSUE TITLE
Authentication error in MSAL.

### ISSUE THREAD

**Issue by Kit-Law-42** [Azure/BatchExplorer#2350]
**Describe the bug**
After upgrading to 2.10.0, an error message is shown when logging into the Azure AD directory.
Nothing can be done except closing BatchExplorer.exe manually.

**To Reproduce**
Upgrade from 2.8.0 to 2.10.0, and open BatchExplorer.exe. 

**Expected behavior**
Batch Explorer should be able to open and prompt my login info to login Azure AD directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/8088801/126479985-1e21c7cb-87fb-40b1-becb-9a89228bfddb.png)
![image](https://user-images.githubusercontent.com/8088801/126480009-b6205f5a-5b20-43fe-a359-6fe8e7422ac1.png)

**Logs**

> {"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError","level":"error","message":"Error while login endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","stack":"ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.\n    at ClientAuthError.AuthError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:398:24)\n    at new ClientAuthError (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:638:28)\n    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:675:16)\n    at Function.<anonymous> (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:6166:47)\n    at step (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:79:23)\n    at Object.throw (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:60:53)\n    at rejected (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.js:51:65)\n    at ZoneDelegate.invoke (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:386:30)\n    at Zone.run (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:143:47)\n    at C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:891:38","timestamp":"2021-07-21T08:50:13.992Z"}

**Version (please complete the following information):**
OS: Windows 10
Version: 2.10.0-stable.519

**Comment by dpwatrous** [comment]
@Kit-Law-42 are you behind a proxy? I haven't seen this error myself, but it sounds a lot like https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2600

**Comment by ciasom** [comment]
Same issue when upgrading to 2.10.0-stable.519. 
Reinstalled previously downloaded 2.7.0-stable.418. 

@dpwatrous , my laptop is behind the corporate proxy.

**Comment by eedokl** [comment]
Hi
I am working at Bosch, corporate network behind firewall and face the very same problem.
