### ISSUE TITLE
Unable to authenticate with latest version 2.11.0-stable.541

### ISSUE THREAD

**Issue by vkesavarao** [Azure/BatchExplorer#2377]
**Describe the bug**
I've downloaded the latest installer and portable version of 2.11.0-stable.541 . But i could not be able to login and getting "Failed to decode Jwt token. The token has invalid format. Actual token: '' popup and asking to login again. But i could not be able to proceed. But with older version "2.9.0-stable.511" with same credentials i am able to authenticate and similar issue is observed to all my colleagues also. 

**Expected behavior**
Able to login with latest versions also.

**Screenshots**

**Logs(Click profile > View Logs > app.log, client.log)**
Find the attached log files

**Version (please complete the following information):**
 - OS: [Windows 
 - Version 10
![Version 2 11 0-stable 541-loginIssue](https://user-images.githubusercontent.com/33343866/130237193-163e35ab-ff68-41e9-8b89-0be732bc182c.PNG)
[logs.zip](https://github.com/Azure/BatchExplorer/files/7021627/logs.zip)

**Comment by dpwatrous** [comment]
@vkesavarao we switched to a different authentication library in this latest stable release. If you try again let us know if you're still seeing the issue.
