### ISSUE TITLE
Authentication Failure with Multi-Tenant Configured Account

### ISSUE THREAD

**Issue by sfarhand** [Azure/BatchExplorer#2380]
My corporate account is associated with multiple tenant IDs. When I run the batch explorer and login, the batch explorer takes the default tenant id, which leads to a failure in authentication. 

![image](https://user-images.githubusercontent.com/8673695/131053489-1a179cc7-52b8-4460-94c4-57df600d4d0f.png)

I have tried deleting the batch explorer folders in %appdata% and it did not solve the issue.

I also tried clearing the accounts, which also did not work:

az account clear 
az login
az set --subscription "correct subscription"

OS: Windows

Log data from console:

info: [BatchExplorer Main] Program arguments {"commands":[],"options":[{"flags":"-V, --version","required":false,"optional":false,"bool":true,"short":"-V","long":"--version","description":"output the version number"},{"flags":"--disable-auto-update","required":false,"optional":false,"bool":true,"long":"--disable-auto-update","description":"Disables autoupdate for one instance of opening up the application"},{"flags":"--updated","required":false,"optional":false,"bool":true,"long":"--updated","description":"If the application was just updated"},{"flags":"--user-data-dir <path>","required":true,"optional":false,"bool":true,"long":"--user-data-dir","description":"Change the user data directory. Used for tests"},{"flags":"--ignore-certificate-errors","required":false,"optional":false,"bool":true,"long":"--ignore-certificate-errors","description":"Ignore https certificate errors"}],"_execs":{},"_allowUnknownOption":false,"_args":[],"_name":"BatchExplorer.exe","_version":"2.11.0-stable.541","_versionOptionName":"version","_events":{},"_eventsCount":5,"rawArgs":["","C:\\Program Files\\BatchExplorer\\BatchExplorer.exe"],"args":[]}
info: [BatchExplorer Main] Registered ms-batch-explorer:// as a protocol for Batch Explorer
info: [BatchExplorer Main] Registered ms-batchlabs:// as a protocol for Batch Explorer
info: [BatchExplorer Main] Python path is: 'C:\Program Files\BatchExplorer\resources\python-rpc\main', Args: 45032
info: [BatchExplorer Python] ========================= STARTING PYTHON RPC SERVER PROCESS =========================
info: [BatchExplorer Main] Python Rpc server started!
info: [BatchExplorer Python] Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "main.py", line 26, in run
  File "server\websocket_server.py", line 17, in __init__
  File "site-packages\websockets\imports.py", line 81, in __getattr__
  File "site-packages\websockets\imports.py", line 26, in import_name
ModuleNotFoundError: No module named 'websockets.legacy'
[24768] Failed to execute script main

info: [BatchExplorer Main] Checking for update
info: [BatchExplorer Main] Checking for update (already in progress)
info: [BatchExplorer Main] Update for version 2.11.0-stable.541 is not available (latest version: 2.11.0-stable.541, downgrade is allowed).
info: [BatchExplorer Renderer] Websocket connection closed. Retrying to connect in 1s
info: [BatchExplorer Renderer] Websocket connection closed. Retrying to connect in 2s
info: [BatchExplorer Renderer] Websocket connection closed. Retrying to connect in 4s
info: [BatchExplorer Renderer] Websocket connection closed. Retrying to connect in 8s
error: [BatchExplorer Main] Error redeem auth code for a token for resource arm invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.
Trace ID: 4ae5e074-5607-499a-9bd5-0952c209d700
Correlation ID: d42821e8-85ba-468a-a490-0d8deb0a793c
Timestamp: 2021-08-27 00:21:52Z {"errorCode":"invalid_grant","errorMessage":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z","subError":"basic_action","name":"InteractionRequiredAuthError","stack":"InteractionRequiredAuthError: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z\n    at InteractionRequiredAuthError.AuthError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:449:24)\n    at InteractionRequiredAuthError.ServerError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:2882:28)\n    at new InteractionRequiredAuthError (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:3835:28)\n    at ResponseHandler.validateTokenResponse (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4362:23)\n    at AuthorizationCodeClient.<anonymous> (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4623:41)\n    at step (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:79:23)\n    at Object.next (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:60:53)\n    at fulfilled (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:50:58)\n    at ZoneDelegate.invoke (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:386:30)\n    at Zone.run (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:143:47)"}
error: [BatchExplorer Main] Error login in  invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.
Trace ID: 4ae5e074-5607-499a-9bd5-0952c209d700
Correlation ID: d42821e8-85ba-468a-a490-0d8deb0a793c
Timestamp: 2021-08-27 00:21:52Z {"errorCode":"invalid_grant","errorMessage":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z","subError":"basic_action","name":"InteractionRequiredAuthError","stack":"InteractionRequiredAuthError: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z\n    at InteractionRequiredAuthError.AuthError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:449:24)\n    at InteractionRequiredAuthError.ServerError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:2882:28)\n    at new InteractionRequiredAuthError (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:3835:28)\n    at ResponseHandler.validateTokenResponse (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4362:23)\n    at AuthorizationCodeClient.<anonymous> (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4623:41)\n    at step (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:79:23)\n    at Object.next (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:60:53)\n    at fulfilled (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:50:58)\n    at ZoneDelegate.invoke (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:386:30)\n    at Zone.run (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:143:47)"}
error: [BatchExplorer Main] Error while login invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.
Trace ID: 4ae5e074-5607-499a-9bd5-0952c209d700
Correlation ID: d42821e8-85ba-468a-a490-0d8deb0a793c
Timestamp: 2021-08-27 00:21:52Z {"errorCode":"invalid_grant","errorMessage":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z","subError":"basic_action","name":"InteractionRequiredAuthError","stack":"InteractionRequiredAuthError: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'wrong tenant id'.\r\nTrace ID: 4ae5e074-5607-499a-9bd5-0952c209d700\r\nCorrelation ID: d42821e8-85ba-468a-a490-0d8deb0a793c\r\nTimestamp: 2021-08-27 00:21:52Z\n    at InteractionRequiredAuthError.AuthError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:449:24)\n    at InteractionRequiredAuthError.ServerError [as constructor] (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:2882:28)\n    at new InteractionRequiredAuthError (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:3835:28)\n    at ResponseHandler.validateTokenResponse (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4362:23)\n    at AuthorizationCodeClient.<anonymous> (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:4623:41)\n    at step (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:79:23)\n    at Object.next (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:60:53)\n    at fulfilled (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:50:58)\n    at ZoneDelegate.invoke (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:386:30)\n    at Zone.run (C:\\Program Files\\BatchExplorer\\resources\\app.asar\\node_modules\\zone.js\\dist\\zone-node.js:143:47)"}
error: [BatchExplorer Renderer] Error loading subscriptions {"0":{"message":"no elements in sequence","name":"EmptyError"}}
D pid(29300) tid(10852) 20:21:56 EdgeSnapFeature::PostExitSizeMove: WM_TWINVIEW_SHOW_GRIDLINES -> off
info: [BatchExplorer Main] Window AuthenticationWindow closed. Quiting the app.
info: [BatchExplorer Main] Stopping python rpc server!
info: [BatchExplorer Main] Window SplashScreen closed. Quiting the app.
info: [BatchExplorer Main] Stopping python rpc server!
info: [BatchExplorer Main] Python rpc server has stopped!
info: [BatchExplorer Main] Stopping python rpc server!

**Comment by gingi** [comment]
This has been addressed with PR #2387, and can be tested on the [Insider Build](https://azure.github.io/BatchExplorer/insider.html). To be released to the stable release later this month.
