### ISSUE TITLE
Authentication: use same method as StorageExplorer

### ISSUE THREAD

**Issue by rfernand2** [Azure/BatchExplorer#2408]
**Is your feature request related to a problem? Please describe.**
Searching the issues for BatchExplorer, I see many problems related to authentication, including #2406, submitted by me.  Even if all these issues were fixed, it is still frustrating to have to do a separate authentication in BatchExplorer.  Why not just do what StorageExplorer does (leverage the Azure website authentication), so user only has to log into Azure once, and it persists for multiple days/weeks?  This may also fix many of the other authentication issues in BatchExplorer.

**Describe the solution you'd like**
Don't have a separate authentication in BatchExplorer; use the Azure website authentication, as does StorageExplorer (as I understand it).

**Comment by dpwatrous** [comment]
This should be the case as of https://github.com/Azure/BatchExplorer/pull/2321 which was included in the most recent stable release. We now use the same underlying authentication library as Storage Explorer (MSAL).
