### ISSUE TITLE
Unable to login with an AAD account that have Conditional Access enabled

### ISSUE THREAD

**Issue by cruiserkernan** [Azure/BatchExplorer#2446]
Ever since our company enabled Conditional Access on our AAD accounts we are no longer able to login in Batch Explorer.

This is the error message:
![image](https://user-images.githubusercontent.com/18163103/153874855-d0c0cc3c-beb3-4d74-8fe8-e823f660b4af.png)

Error Code: 53000
Request Id: *****
Correlation Id: *****
Timestamp: 2022-02-14T13:38:41.083Z
App name: Microsoft Azure CLI
App id: *****
IP address: *****
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

When looking at the login attempt in Azure AD I can see that it gets rejected because it is not a Compliant device.
Specifically it the **Access controls - Grant Controls** that is rejecting the login attempt.

How can we fix this without enabling all chromium based devices?

**Comment by AntonyHarnist** [comment]
Hi there,

It seems like I have the same issue.

Error Code: 53000
Request Id: ******
Correlation Id: ******
Timestamp: 2022-06-15T09:31:39.146Z
App name: Microsoft Azure CLI
App id: ******
IP address: ******
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

Any development on this issue?

**Comment by gingi** [comment]
Can you download the [insider build](https://azure.github.io/BatchExplorer/insider.html) and see if it addresses your issue?

**Comment by AntonyHarnist** [comment]
I still have the issue even after installing insider build.

**Comment by yggdrasil-tynor** [comment]
Still not possible with insider 911

**Comment by MichaCo** [comment]
Having the same issue. Is there a workaround, like using a token or something instead?
![image](https://github.com/Azure/BatchExplorer/assets/5837539/7b544bff-4f63-4c6c-9537-452425d6e984)


It is really crucial for me to be able to manage our production processes and right now, only with the very limited UI of the Azure dashboard, its impossible to analyze any errors or anything really...

Thanks

**Comment by webfatal** [comment]
Same here on my side. Since the activation of "Windows hello" in AD / AAD, the Batch Explorer is not working anymore. Is there any workaround? The tool is really great and helpful - so it would be really cool to have it working again even with the latestes security and hardening settings by lartge enterprises.

**Comment by MichaCo** [comment]
> Can you download the [insider build](https://azure.github.io/BatchExplorer/insider.html) and see if it addresses your issue?

@gingi I tested both, the latest stable and latest insider build and I still cannot login and use this app.

```
Error Code: 53000
Request Id: **
Correlation Id: **
Timestamp: 2024-01-25T13:43:45.247Z
App name: Microsoft Azure CLI
App ID: **
IP address: **
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered
```

Any update on this issue or suggestion for my IT department how to configure AD for this app?  ;)

Can I maybe bypass that rule for "App name: Microsoft Azure CLI"?
I think you can whitelist devices by ID but this one shows N/A, so, I guess that wouldn't work?

Thanks

**Comment by DaveyBiggers** [comment]
Any news on this? I'm also getting the "You can't get there from here" message when I try to run.

**Comment by dpwatrous** [comment]
Just a quick update: I created a [PR](https://github.com/Azure/BatchExplorer/commit/b3149337b4c0dfc7d4f70a5a1296ca419c209bdb) to support auth using the default system browser, which should give us full conditional access support, assuming the default browser is compliant. 

This will need some testing to make sure we didn't break any other auth flows, but I'm hoping we can get this in an insiders build this week, with a stable release coming next month.

**Comment by yuanyuanwho** [comment]
Any update on this? Still see the same error with latest version

**Comment by rossdakin** [comment]
+1

**Comment by BMurri** [comment]
Any progress? This is blocking use of a very valuable productivity tool (namely, Batch Explorer).

Anything I could do to help?

**Comment by MichaCo** [comment]
@gingi would it be possible to get an insider build of that PR, I could test it for you for free at least ;) 
And, if it works, it would help me a lot of getting some work done... 

Working with Azure batch without this UI is insanely difficult because the default azure UI is so bad for this service...
