### ISSUE TITLE
Job Schaduler tab has dissapear from azure batch explorer

### ISSUE THREAD

**Issue by jroales** [Azure/BatchExplorer#2540]
**Describe the bug**
Until two days ago, in the tool the option to work with jo and with jobs scheduler appeared on the right side, for 2 days the job scheduler option has disappeared.
I have tried to reinstall the tool, but still the same.
a greeting

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42235052/177989974-3b41c9ce-7c34-4f8e-ae63-d65d6042c7c1.png)

**Logs(Click profile > View Logs > app.log, client.log)**
If applicable please attach those log files

**Version (please complete the following information):**
 - OS: [Windows/Osx/Linux]
 - Version [e.g. 0.15.2]

**Comment by cRui861** [comment]
Hi @jroales, could you check the bottom left hand corner of your application and see which workspace you're in (see screenshot below)? If you're in Basic end-user workspace then some of the left hand tabs aren't available. If you switch back to Admin/Developer workspace you should see the Job Scheduler option again.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/16728220/178051314-3cc6e512-9262-4f92-ad2a-66cea1ac7bef.png">

**Comment by jroales** [comment]
Thanks! it is working.!
