### ISSUE TITLE
Unable to sign in using Windows Hello or a security key

### ISSUE THREAD

**Issue by wipash** [Azure/BatchExplorer#2586]
**Describe the bug**
When trying to sign in, I'm required to pass an MFA check using either Windows Hello or a security key (as per our company policy). BatchExplorer presents the sign in window, but just sits loading forever and Windows never prompts for a security key or Windows Hello.

**To Reproduce**
1. Configure a conditional access policy that requires phishing-resistant MFA
2. Start BatchExplorer
3. Sign in

**Expected behavior**
Windows should prompt me to tap my security key, or to pass a Windows Hello check

**Screenshots**
![image](https://user-images.githubusercontent.com/2068349/199864331-c6493e5d-968a-4d73-917b-e774a14c5164.png)

**Logs(Click profile > View Logs > app.log, client.log)**
No messages appear in the developer tools console.

**Version (please complete the following information):**
 - OS: Windows 11
 - Build: 2.16.0-insider.641

**Comment by gingi** [comment]
Duplicate of #2446. There are known issues with MSAL support for Conditional Access regarding the exchange of device ID for device code flow. We are working on a solution to deal with this shortcoming.
