### ISSUE TITLE
Python backend disconnected in version 2.16.1-stable.713

### ISSUE THREAD

**Issue by windengineer0** [Azure/BatchExplorer#2662]
**Describe the bug**
A new installation of the latest stable version results in the "Python backend disconnected" message. Looking in the python-server.log file, it appears to be a ModuleNotFoundError. 

With this being disconnected, it is not possible to perform basic tasks such as uploading a new version of an application package (Error: "Unable to extract accountName with provided information.")

**To Reproduce**
1. Log into BatchExplorer
2. Click on Python Backend message at the bottom bar.

**Expected behavior**
In version 2.15.0-stable.634, "Python service is connected and running".

**Screenshots**
N/A

**Logs(Click profile > View Logs > app.log, client.log)**
```
info: ========================= STARTING PYTHON RPC SERVER PROCESS =========================
info: Traceback (most recent call last):
  File "main.py", line 8, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "server\websocket_server.py", line 4, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "jsonrpc\__init__.py", line 6, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "jsonrpc\request.py", line 5, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "server\aad_auth.py", line 1, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "azext\batch\__init__.py", line 6, in <module>

info:   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module

info:   File "azext\batch\batch_extensions_client.py", line 14, in <module>

info: ModuleNotFoundError: No module named 'azure.multiapi'
[3712] Failed to execute script
info:  'main' due to 
info: unhandled exception!
```

**Version (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 21H2
 - Build 19044.2486

**Comment by dpwatrous** [comment]
+@gingi
