### ISSUE TITLE
Allows users to select browser for authentication during reauthenticate flow

### ISSUE THREAD

**Issue by illgitthat** [Azure/BatchExplorer#2933]
Branching the below from #2910 into a new issue.

This is fixed but is still an issue when going through the "reauthenticate" flow within tenants.

Example flow to reproduce:

* Download batch explorer and authenticate with web browser login flow
* Close it out and wait some time for authentication to expire
* Attempt to reauthenticate with this button

![image](https://github.com/user-attachments/assets/413f5811-da8d-40d4-b17d-13b90b765825)

Receive the below error.

Following up here @gingi - this worked for me on initial download and startup but then when I was timed out / tried to reauthenticate I ran into the same error.

![image](https://github.com/user-attachments/assets/ab073f86-9c83-46cb-8baf-235189e39746)

_Originally posted by @illgitthat in https://github.com/Azure/BatchExplorer/issues/2910#issuecomment-2326814880_

**Comment by gingi** [comment]
This has been fixed in PR #2928
