### ISSUE TITLE
Cannot use proxy settings window

### ISSUE THREAD

**Issue by helder2002** [Azure/BatchExplorer#2937]
**Describe the bug**
When trying to use the built in proxy settings window it seems that nothing happens. The save button and the clear button does not seem to work.

**To Reproduce**
1. Go to Edit
2. Click on 'Configure Proxy'
3. Enter proxy configuration for Batch Explorer Window will open

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f93cebab-996e-401b-9940-ea7652b067c0)

**Version (please complete the following information):**
 - OS: Windows
 - Version 11.2.0

**Comment by gingi** [comment]
This has been fixed with PR #2938.
