### ISSUE TITLE
Support additional Gallery repositories

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchExplorer#955]
It would be great to be able to add additional repositories to the BL gallery.  This would aid people that want to maintain their own versions, but also make it easier to test changes before merging them to master.  I'm aware that you can use 'local' templates, but this doesn't solve all these problems.

One other option would be to support 'local repositories insame manner as the GitHub repos, this would be an extension to the current local templates support.

**Comment by ascobie** [comment]
we could add a section in "user settings" for this. either override the branch for the BL-data repo, or add forked repos collection. Having a consistent repo layout would be key as reading any old repo could prove problematic. But a fork of BL-data could work well.

**Comment by smith1511** [comment]
I really think this would be useful to be honest and like your suggestion.  Although ideally multiple repositories, i.e. default and others?  A key to this would be using private repos too, i.e. with credentials as some people have scripts and sensitive info in scripts that they can't make public.

**Comment by timotheeguerin** [comment]
So I didn't really get this then, but I think the idea here is that people fork the batchlabs-data repo and use that version as the data source?
